language: python
python:
- '3.6'
install:
script: python setup.py test
deploy:
  provider: pypi
  user: swegener
  on:
    tags: true
  password:
    secure: "Rt2261FfCM4W95+h6RJaPGKdrcFXXG2Tf5YbMi2sDyZad1M1OnZ1pplxq3dwSQ8rHPWaqsrt4EWWeEXINK0a2F4teNzTL2kPjGDhK4ipVqrwo8NWT7tIfql7nyUAFdxVvfn6DT6hMs3oU0NVL4wqv/LanjwxP5F07IhtS8tdLfOBHfNHUmNfyrmMstUm1kcULxtw1Ud104+9/qWT4VoaZ5zZGaEEImiP8u0Nm7QXk4SCwE/qhhGiSfBjmgtHwwwgdOKdkcu3iq/lKXc/2JUWkisSkoYec2AyUPbIax9J9tK85c9Yozw3DbMr6nXsYNeC9kc5XDQWX6UbZr2L78/8G3LEVr1CU3cEtAwSm/ZcTZSskNv0ZHpN9do6T3mjtfjxsUqm1Zm/Wnlc60+T7MXuXB/0wOhLbhCMPYzyihMOU4SbGdNyZVodg2TmdBRiRLBTzGAJSi5vROKQhnU7sZ4MkJ1hHciMGMuQaToUEUBW8WjFKfRC/4XoOt8tqz0Jm1pwoqomQseN6tvHRl5q7n+Zwgsx5h1rCNTKlCPsyv7dOXkLGLQ6QC43Gmj3SMrooQvcVLogglzzzxFFB5nV/P3jCkChNl55+1lUXfZrrvDfi4jyISgclOA/HSbsGUSmsnkTmDzbCYUvwy1Oat+BBuIjWgH0v8aoFCBId0nF1Kkry0c="
